//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CommandLine.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Butjok {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public partial class CommandLineLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		Semicolon=1, LeftParenthesis=2, RightParenthesis=3, Comma=4, Vector2Int=5, 
		Color=6, True=7, False=8, Integer=9, Real=10, DoubleQuotedString=11, Name=12, 
		ShortHexRgbColor=13, ShortHexRgbaColor=14, LongHexRgbColor=15, LongHexRgbaColor=16, 
		SingleLineComment=17, BlockComment=18, Whitespace=19;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"Semicolon", "LeftParenthesis", "RightParenthesis", "Comma", "Vector2Int", 
		"Color", "True", "False", "Integer", "Real", "DoubleQuotedString", "Name", 
		"ShortHexRgbColor", "ShortHexRgbaColor", "LongHexRgbColor", "LongHexRgbaColor", 
		"Word", "HexadecimalDigit", "SingleLineComment", "BlockComment", "Whitespace"
	};


	public CommandLineLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public CommandLineLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "';'", "'('", "')'", "','", "'Vector2Int'", "'Color'", "'true'", 
		"'false'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "Semicolon", "LeftParenthesis", "RightParenthesis", "Comma", "Vector2Int", 
		"Color", "True", "False", "Integer", "Real", "DoubleQuotedString", "Name", 
		"ShortHexRgbColor", "ShortHexRgbaColor", "LongHexRgbColor", "LongHexRgbaColor", 
		"SingleLineComment", "BlockComment", "Whitespace"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "CommandLine.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static CommandLineLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x15', '\xC9', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\n', '\x5', '\n', 'S', '\n', '\n', '\x3', '\n', '\x6', 
		'\n', 'V', '\n', '\n', '\r', '\n', '\xE', '\n', 'W', '\x3', '\v', '\x5', 
		'\v', '[', '\n', '\v', '\x3', '\v', '\a', '\v', '^', '\n', '\v', '\f', 
		'\v', '\xE', '\v', '\x61', '\v', '\v', '\x3', '\v', '\x3', '\v', '\x6', 
		'\v', '\x65', '\n', '\v', '\r', '\v', '\xE', '\v', '\x66', '\x3', '\v', 
		'\x6', '\v', 'j', '\n', '\v', '\r', '\v', '\xE', '\v', 'k', '\x3', '\v', 
		'\x5', '\v', 'o', '\n', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\a', '\f', 'u', '\n', '\f', '\f', '\f', '\xE', '\f', 'x', '\v', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\a', '\r', '\x7F', '\n', '\r', '\f', '\r', '\xE', '\r', '\x82', '\v', 
		'\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', 
		'\x3', '\x12', '\a', '\x12', '\xA3', '\n', '\x12', '\f', '\x12', '\xE', 
		'\x12', '\xA6', '\v', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\a', '\x14', '\xAE', '\n', 
		'\x14', '\f', '\x14', '\xE', '\x14', '\xB1', '\v', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\a', '\x15', '\xB9', '\n', '\x15', '\f', '\x15', '\xE', '\x15', '\xBC', 
		'\v', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x16', '\x6', '\x16', '\xC4', '\n', '\x16', '\r', 
		'\x16', '\xE', '\x16', '\xC5', '\x3', '\x16', '\x3', '\x16', '\x3', '\xBA', 
		'\x2', '\x17', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', 
		'\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', 
		'\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', 
		'!', '\x12', '#', '\x2', '%', '\x2', '\'', '\x13', ')', '\x14', '+', '\x15', 
		'\x3', '\x2', '\n', '\x3', '\x2', '\x32', ';', '\a', '\x2', '$', '$', 
		'^', '^', 'p', 'p', 't', 't', 'v', 'v', '\x5', '\x2', '\x2', '!', '$', 
		'$', '^', '^', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', 
		'\x6', '\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', '|', 
		'\x5', '\x2', '\x32', ';', '\x43', 'H', '\x63', 'h', '\x4', '\x2', '\f', 
		'\f', '\xF', '\xF', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', 
		'\x2', '\xD4', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'!', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', 
		'\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '-', '\x3', '\x2', '\x2', '\x2', '\x5', '/', '\x3', '\x2', 
		'\x2', '\x2', '\a', '\x31', '\x3', '\x2', '\x2', '\x2', '\t', '\x33', 
		'\x3', '\x2', '\x2', '\x2', '\v', '\x35', '\x3', '\x2', '\x2', '\x2', 
		'\r', '@', '\x3', '\x2', '\x2', '\x2', '\xF', '\x46', '\x3', '\x2', '\x2', 
		'\x2', '\x11', 'K', '\x3', '\x2', '\x2', '\x2', '\x13', 'R', '\x3', '\x2', 
		'\x2', '\x2', '\x15', 'Z', '\x3', '\x2', '\x2', '\x2', '\x17', 'p', '\x3', 
		'\x2', '\x2', '\x2', '\x19', '{', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'\x83', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x88', '\x3', '\x2', '\x2', 
		'\x2', '\x1F', '\x8E', '\x3', '\x2', '\x2', '\x2', '!', '\x96', '\x3', 
		'\x2', '\x2', '\x2', '#', '\xA0', '\x3', '\x2', '\x2', '\x2', '%', '\xA7', 
		'\x3', '\x2', '\x2', '\x2', '\'', '\xA9', '\x3', '\x2', '\x2', '\x2', 
		')', '\xB4', '\x3', '\x2', '\x2', '\x2', '+', '\xC3', '\x3', '\x2', '\x2', 
		'\x2', '-', '.', '\a', '=', '\x2', '\x2', '.', '\x4', '\x3', '\x2', '\x2', 
		'\x2', '/', '\x30', '\a', '*', '\x2', '\x2', '\x30', '\x6', '\x3', '\x2', 
		'\x2', '\x2', '\x31', '\x32', '\a', '+', '\x2', '\x2', '\x32', '\b', '\x3', 
		'\x2', '\x2', '\x2', '\x33', '\x34', '\a', '.', '\x2', '\x2', '\x34', 
		'\n', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\a', 'X', '\x2', '\x2', 
		'\x36', '\x37', '\a', 'g', '\x2', '\x2', '\x37', '\x38', '\a', '\x65', 
		'\x2', '\x2', '\x38', '\x39', '\a', 'v', '\x2', '\x2', '\x39', ':', '\a', 
		'q', '\x2', '\x2', ':', ';', '\a', 't', '\x2', '\x2', ';', '<', '\a', 
		'\x34', '\x2', '\x2', '<', '=', '\a', 'K', '\x2', '\x2', '=', '>', '\a', 
		'p', '\x2', '\x2', '>', '?', '\a', 'v', '\x2', '\x2', '?', '\f', '\x3', 
		'\x2', '\x2', '\x2', '@', '\x41', '\a', '\x45', '\x2', '\x2', '\x41', 
		'\x42', '\a', 'q', '\x2', '\x2', '\x42', '\x43', '\a', 'n', '\x2', '\x2', 
		'\x43', '\x44', '\a', 'q', '\x2', '\x2', '\x44', '\x45', '\a', 't', '\x2', 
		'\x2', '\x45', '\xE', '\x3', '\x2', '\x2', '\x2', '\x46', 'G', '\a', 'v', 
		'\x2', '\x2', 'G', 'H', '\a', 't', '\x2', '\x2', 'H', 'I', '\a', 'w', 
		'\x2', '\x2', 'I', 'J', '\a', 'g', '\x2', '\x2', 'J', '\x10', '\x3', '\x2', 
		'\x2', '\x2', 'K', 'L', '\a', 'h', '\x2', '\x2', 'L', 'M', '\a', '\x63', 
		'\x2', '\x2', 'M', 'N', '\a', 'n', '\x2', '\x2', 'N', 'O', '\a', 'u', 
		'\x2', '\x2', 'O', 'P', '\a', 'g', '\x2', '\x2', 'P', '\x12', '\x3', '\x2', 
		'\x2', '\x2', 'Q', 'S', '\a', '/', '\x2', '\x2', 'R', 'Q', '\x3', '\x2', 
		'\x2', '\x2', 'R', 'S', '\x3', '\x2', '\x2', '\x2', 'S', 'U', '\x3', '\x2', 
		'\x2', '\x2', 'T', 'V', '\t', '\x2', '\x2', '\x2', 'U', 'T', '\x3', '\x2', 
		'\x2', '\x2', 'V', 'W', '\x3', '\x2', '\x2', '\x2', 'W', 'U', '\x3', '\x2', 
		'\x2', '\x2', 'W', 'X', '\x3', '\x2', '\x2', '\x2', 'X', '\x14', '\x3', 
		'\x2', '\x2', '\x2', 'Y', '[', '\a', '/', '\x2', '\x2', 'Z', 'Y', '\x3', 
		'\x2', '\x2', '\x2', 'Z', '[', '\x3', '\x2', '\x2', '\x2', '[', 'n', '\x3', 
		'\x2', '\x2', '\x2', '\\', '^', '\t', '\x2', '\x2', '\x2', ']', '\\', 
		'\x3', '\x2', '\x2', '\x2', '^', '\x61', '\x3', '\x2', '\x2', '\x2', '_', 
		']', '\x3', '\x2', '\x2', '\x2', '_', '`', '\x3', '\x2', '\x2', '\x2', 
		'`', '\x62', '\x3', '\x2', '\x2', '\x2', '\x61', '_', '\x3', '\x2', '\x2', 
		'\x2', '\x62', '\x64', '\a', '\x30', '\x2', '\x2', '\x63', '\x65', '\t', 
		'\x2', '\x2', '\x2', '\x64', '\x63', '\x3', '\x2', '\x2', '\x2', '\x65', 
		'\x66', '\x3', '\x2', '\x2', '\x2', '\x66', '\x64', '\x3', '\x2', '\x2', 
		'\x2', '\x66', 'g', '\x3', '\x2', '\x2', '\x2', 'g', 'o', '\x3', '\x2', 
		'\x2', '\x2', 'h', 'j', '\t', '\x2', '\x2', '\x2', 'i', 'h', '\x3', '\x2', 
		'\x2', '\x2', 'j', 'k', '\x3', '\x2', '\x2', '\x2', 'k', 'i', '\x3', '\x2', 
		'\x2', '\x2', 'k', 'l', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\x3', '\x2', 
		'\x2', '\x2', 'm', 'o', '\a', '\x30', '\x2', '\x2', 'n', '_', '\x3', '\x2', 
		'\x2', '\x2', 'n', 'i', '\x3', '\x2', '\x2', '\x2', 'o', '\x16', '\x3', 
		'\x2', '\x2', '\x2', 'p', 'v', '\a', '$', '\x2', '\x2', 'q', 'r', '\a', 
		'^', '\x2', '\x2', 'r', 'u', '\t', '\x3', '\x2', '\x2', 's', 'u', '\n', 
		'\x4', '\x2', '\x2', 't', 'q', '\x3', '\x2', '\x2', '\x2', 't', 's', '\x3', 
		'\x2', '\x2', '\x2', 'u', 'x', '\x3', '\x2', '\x2', '\x2', 'v', 't', '\x3', 
		'\x2', '\x2', '\x2', 'v', 'w', '\x3', '\x2', '\x2', '\x2', 'w', 'y', '\x3', 
		'\x2', '\x2', '\x2', 'x', 'v', '\x3', '\x2', '\x2', '\x2', 'y', 'z', '\a', 
		'$', '\x2', '\x2', 'z', '\x18', '\x3', '\x2', '\x2', '\x2', '{', '\x80', 
		'\x5', '#', '\x12', '\x2', '|', '}', '\a', '\x30', '\x2', '\x2', '}', 
		'\x7F', '\x5', '#', '\x12', '\x2', '~', '|', '\x3', '\x2', '\x2', '\x2', 
		'\x7F', '\x82', '\x3', '\x2', '\x2', '\x2', '\x80', '~', '\x3', '\x2', 
		'\x2', '\x2', '\x80', '\x81', '\x3', '\x2', '\x2', '\x2', '\x81', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', '\x82', '\x80', '\x3', '\x2', '\x2', '\x2', 
		'\x83', '\x84', '\a', '%', '\x2', '\x2', '\x84', '\x85', '\x5', '%', '\x13', 
		'\x2', '\x85', '\x86', '\x5', '%', '\x13', '\x2', '\x86', '\x87', '\x5', 
		'%', '\x13', '\x2', '\x87', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x88', 
		'\x89', '\a', '%', '\x2', '\x2', '\x89', '\x8A', '\x5', '%', '\x13', '\x2', 
		'\x8A', '\x8B', '\x5', '%', '\x13', '\x2', '\x8B', '\x8C', '\x5', '%', 
		'\x13', '\x2', '\x8C', '\x8D', '\x5', '%', '\x13', '\x2', '\x8D', '\x1E', 
		'\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', '\a', '%', '\x2', '\x2', '\x8F', 
		'\x90', '\x5', '%', '\x13', '\x2', '\x90', '\x91', '\x5', '%', '\x13', 
		'\x2', '\x91', '\x92', '\x5', '%', '\x13', '\x2', '\x92', '\x93', '\x5', 
		'%', '\x13', '\x2', '\x93', '\x94', '\x5', '%', '\x13', '\x2', '\x94', 
		'\x95', '\x5', '%', '\x13', '\x2', '\x95', ' ', '\x3', '\x2', '\x2', '\x2', 
		'\x96', '\x97', '\a', '%', '\x2', '\x2', '\x97', '\x98', '\x5', '%', '\x13', 
		'\x2', '\x98', '\x99', '\x5', '%', '\x13', '\x2', '\x99', '\x9A', '\x5', 
		'%', '\x13', '\x2', '\x9A', '\x9B', '\x5', '%', '\x13', '\x2', '\x9B', 
		'\x9C', '\x5', '%', '\x13', '\x2', '\x9C', '\x9D', '\x5', '%', '\x13', 
		'\x2', '\x9D', '\x9E', '\x5', '%', '\x13', '\x2', '\x9E', '\x9F', '\x5', 
		'%', '\x13', '\x2', '\x9F', '\"', '\x3', '\x2', '\x2', '\x2', '\xA0', 
		'\xA4', '\t', '\x5', '\x2', '\x2', '\xA1', '\xA3', '\t', '\x6', '\x2', 
		'\x2', '\xA2', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA6', '\x3', 
		'\x2', '\x2', '\x2', '\xA4', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA4', 
		'\xA5', '\x3', '\x2', '\x2', '\x2', '\xA5', '$', '\x3', '\x2', '\x2', 
		'\x2', '\xA6', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA8', '\t', 
		'\a', '\x2', '\x2', '\xA8', '&', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xAA', 
		'\a', '\x31', '\x2', '\x2', '\xAA', '\xAB', '\a', '\x31', '\x2', '\x2', 
		'\xAB', '\xAF', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAE', '\n', '\b', 
		'\x2', '\x2', '\xAD', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xB1', 
		'\x3', '\x2', '\x2', '\x2', '\xAF', '\xAD', '\x3', '\x2', '\x2', '\x2', 
		'\xAF', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB2', '\x3', '\x2', 
		'\x2', '\x2', '\xB1', '\xAF', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB3', 
		'\b', '\x14', '\x2', '\x2', '\xB3', '(', '\x3', '\x2', '\x2', '\x2', '\xB4', 
		'\xB5', '\a', '\x31', '\x2', '\x2', '\xB5', '\xB6', '\a', ',', '\x2', 
		'\x2', '\xB6', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xB7', '\xB9', '\v', 
		'\x2', '\x2', '\x2', '\xB8', '\xB7', '\x3', '\x2', '\x2', '\x2', '\xB9', 
		'\xBC', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xBB', '\x3', '\x2', '\x2', 
		'\x2', '\xBA', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xBD', '\x3', 
		'\x2', '\x2', '\x2', '\xBC', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xBD', 
		'\xBE', '\a', ',', '\x2', '\x2', '\xBE', '\xBF', '\a', '\x31', '\x2', 
		'\x2', '\xBF', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xC1', '\b', 
		'\x15', '\x2', '\x2', '\xC1', '*', '\x3', '\x2', '\x2', '\x2', '\xC2', 
		'\xC4', '\t', '\t', '\x2', '\x2', '\xC3', '\xC2', '\x3', '\x2', '\x2', 
		'\x2', '\xC4', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC3', '\x3', 
		'\x2', '\x2', '\x2', '\xC5', '\xC6', '\x3', '\x2', '\x2', '\x2', '\xC6', 
		'\xC7', '\x3', '\x2', '\x2', '\x2', '\xC7', '\xC8', '\b', '\x16', '\x2', 
		'\x2', '\xC8', ',', '\x3', '\x2', '\x2', '\x2', '\x11', '\x2', 'R', 'W', 
		'Z', '_', '\x66', 'k', 'n', 't', 'v', '\x80', '\xA4', '\xAF', '\xBA', 
		'\xC5', '\x3', '\x2', '\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Butjok
