//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CommandLine.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Butjok {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CommandLineParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public interface ICommandLineVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.colorScheme"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColorScheme([NotNull] CommandLineParser.ColorSchemeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.style"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStyle([NotNull] CommandLineParser.StyleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInput([NotNull] CommandLineParser.InputContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] CommandLineParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.noOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoOperation([NotNull] CommandLineParser.NoOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand([NotNull] CommandLineParser.CommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] CommandLineParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] CommandLineParser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolean([NotNull] CommandLineParser.BooleanContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInteger([NotNull] CommandLineParser.IntegerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.real"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReal([NotNull] CommandLineParser.RealContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] CommandLineParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.int2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt2([NotNull] CommandLineParser.Int2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.color"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColor([NotNull] CommandLineParser.ColorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.shortHexRgbColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShortHexRgbColor([NotNull] CommandLineParser.ShortHexRgbColorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.shortHexRgbaColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShortHexRgbaColor([NotNull] CommandLineParser.ShortHexRgbaColorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.longHexRgbColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLongHexRgbColor([NotNull] CommandLineParser.LongHexRgbColorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.longHexRgbaColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLongHexRgbaColor([NotNull] CommandLineParser.LongHexRgbaColorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.colorComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColorComponent([NotNull] CommandLineParser.ColorComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.rgbColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRgbColor([NotNull] CommandLineParser.RgbColorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CommandLineParser.rgbaColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRgbaColor([NotNull] CommandLineParser.RgbaColorContext context);
}
} // namespace Butjok
