//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CommandLine.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Butjok {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CommandLineParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public interface ICommandLineListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.colorScheme"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColorScheme([NotNull] CommandLineParser.ColorSchemeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.colorScheme"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColorScheme([NotNull] CommandLineParser.ColorSchemeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.style"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStyle([NotNull] CommandLineParser.StyleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.style"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStyle([NotNull] CommandLineParser.StyleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInput([NotNull] CommandLineParser.InputContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInput([NotNull] CommandLineParser.InputContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] CommandLineParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] CommandLineParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.noOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoOperation([NotNull] CommandLineParser.NoOperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.noOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoOperation([NotNull] CommandLineParser.NoOperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommand([NotNull] CommandLineParser.CommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommand([NotNull] CommandLineParser.CommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] CommandLineParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] CommandLineParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] CommandLineParser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] CommandLineParser.VariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean([NotNull] CommandLineParser.BooleanContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean([NotNull] CommandLineParser.BooleanContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteger([NotNull] CommandLineParser.IntegerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteger([NotNull] CommandLineParser.IntegerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.real"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReal([NotNull] CommandLineParser.RealContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.real"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReal([NotNull] CommandLineParser.RealContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] CommandLineParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] CommandLineParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.int2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInt2([NotNull] CommandLineParser.Int2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.int2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInt2([NotNull] CommandLineParser.Int2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.color"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColor([NotNull] CommandLineParser.ColorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.color"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColor([NotNull] CommandLineParser.ColorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.shortHexRgbColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShortHexRgbColor([NotNull] CommandLineParser.ShortHexRgbColorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.shortHexRgbColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShortHexRgbColor([NotNull] CommandLineParser.ShortHexRgbColorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.shortHexRgbaColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShortHexRgbaColor([NotNull] CommandLineParser.ShortHexRgbaColorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.shortHexRgbaColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShortHexRgbaColor([NotNull] CommandLineParser.ShortHexRgbaColorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.longHexRgbColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLongHexRgbColor([NotNull] CommandLineParser.LongHexRgbColorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.longHexRgbColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLongHexRgbColor([NotNull] CommandLineParser.LongHexRgbColorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.longHexRgbaColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLongHexRgbaColor([NotNull] CommandLineParser.LongHexRgbaColorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.longHexRgbaColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLongHexRgbaColor([NotNull] CommandLineParser.LongHexRgbaColorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.colorComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColorComponent([NotNull] CommandLineParser.ColorComponentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.colorComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColorComponent([NotNull] CommandLineParser.ColorComponentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.rgbColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRgbColor([NotNull] CommandLineParser.RgbColorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.rgbColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRgbColor([NotNull] CommandLineParser.RgbColorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CommandLineParser.rgbaColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRgbaColor([NotNull] CommandLineParser.RgbaColorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CommandLineParser.rgbaColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRgbaColor([NotNull] CommandLineParser.RgbaColorContext context);
}
} // namespace Butjok
