// https://github.com/Butjok/CommandLine
// This file was automatically generated by CommandLine/Editor/GenerateTokens.cs

namespace Butjok.CommandLine
{
    public enum Token
    {
        Asterisk = 1,
        DoubleAmpersand = 2,
        DoubleVerticalBar = 3,
        Exclamation = 4,
        False = 5,
        ForwardSlash = 6,
        Identifier = 21,
        Int2 = 7,
        Integer = 22,
        Interpolation = 8,
        LeftCurlyBrace = 9,
        LeftParenthesis = 10,
        LeftSquareBracket = 11,
        Minus = 12,
        Percent = 13,
        Plus = 14,
        Real = 23,
        Rgb = 15,
        RightCurlyBrace = 16,
        RightParenthesis = 17,
        RightSquareBracket = 18,
        Semicolon = 19,
        String = 24,
        True = 20,
        Whitespace = 25,
    }
}
