//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/butjok/CommandLine/Assets/Console/Console.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Butjok.Parsers {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public partial class ConsoleLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, True=2, False=3, Rgb=4, Int2=5, Interpolation=6, LeftCurlyBrace=7, 
		RightCurlyBrace=8, LeftParenthesis=9, RightParenthesis=10, LeftSquareBracket=11, 
		RightSquareBracket=12, Minus=13, Exclamation=14, Asterisk=15, Slash=16, 
		Percent=17, Plus=18, DoubleAmpersand=19, DoubleVerticalBar=20, Identifier=21, 
		String=22, Real=23, Integer=24, Whitespace=25;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "True", "False", "Rgb", "Int2", "Interpolation", "LeftCurlyBrace", 
		"RightCurlyBrace", "LeftParenthesis", "RightParenthesis", "LeftSquareBracket", 
		"RightSquareBracket", "Minus", "Exclamation", "Asterisk", "Slash", "Percent", 
		"Plus", "DoubleAmpersand", "DoubleVerticalBar", "Identifier", "String", 
		"Real", "Integer", "Whitespace", "INT"
	};


	public ConsoleLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ConsoleLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "':'", "'true'", "'false'", "'rgb'", "'int2'", "'$'", "'{'", "'}'", 
		"'('", "')'", "'['", "']'", "'-'", "'!'", "'*'", "'/'", "'%'", "'+'", 
		"'&&'", "'||'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "True", "False", "Rgb", "Int2", "Interpolation", "LeftCurlyBrace", 
		"RightCurlyBrace", "LeftParenthesis", "RightParenthesis", "LeftSquareBracket", 
		"RightSquareBracket", "Minus", "Exclamation", "Asterisk", "Slash", "Percent", 
		"Plus", "DoubleAmpersand", "DoubleVerticalBar", "Identifier", "String", 
		"Real", "Integer", "Whitespace"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Console.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ConsoleLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1B', '\xAB', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', 
		'\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', 
		'\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', 
		'\x16', '\a', '\x16', 'p', '\n', '\x16', '\f', '\x16', '\xE', '\x16', 
		's', '\v', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\a', 
		'\x16', 'x', '\n', '\x16', '\f', '\x16', '\xE', '\x16', '{', '\v', '\x16', 
		'\a', '\x16', '}', '\n', '\x16', '\f', '\x16', '\xE', '\x16', '\x80', 
		'\v', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\a', '\x17', '\x86', '\n', '\x17', '\f', '\x17', '\xE', '\x17', '\x89', 
		'\v', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x5', '\x18', 
		'\x8E', '\n', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x18', '\x5', '\x18', '\x99', '\n', '\x18', '\x3', '\x19', '\x5', '\x19', 
		'\x9C', '\n', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x6', 
		'\x1A', '\xA1', '\n', '\x1A', '\r', '\x1A', '\xE', '\x1A', '\xA2', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x6', '\x1B', '\xA8', '\n', '\x1B', 
		'\r', '\x1B', '\xE', '\x1B', '\xA9', '\x2', '\x2', '\x1C', '\x3', '\x3', 
		'\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', 
		'\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', 
		'\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', 
		'/', '\x19', '\x31', '\x1A', '\x33', '\x1B', '\x35', '\x2', '\x3', '\x2', 
		'\b', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x6', 
		'\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\t', '\x2', 
		'$', '$', '^', '^', '\x64', '\x64', 'h', 'h', 'p', 'p', 't', 't', 'v', 
		'v', '\x5', '\x2', '\x2', '!', '$', '$', '^', '^', '\x5', '\x2', '\v', 
		'\f', '\xF', '\xF', '\"', '\"', '\x3', '\x2', '\x32', ';', '\x2', '\xB4', 
		'\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', 
		')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\x3', '\x37', '\x3', '\x2', '\x2', '\x2', '\x5', 
		'\x39', '\x3', '\x2', '\x2', '\x2', '\a', '>', '\x3', '\x2', '\x2', '\x2', 
		'\t', '\x44', '\x3', '\x2', '\x2', '\x2', '\v', 'H', '\x3', '\x2', '\x2', 
		'\x2', '\r', 'M', '\x3', '\x2', '\x2', '\x2', '\xF', 'O', '\x3', '\x2', 
		'\x2', '\x2', '\x11', 'Q', '\x3', '\x2', '\x2', '\x2', '\x13', 'S', '\x3', 
		'\x2', '\x2', '\x2', '\x15', 'U', '\x3', '\x2', '\x2', '\x2', '\x17', 
		'W', '\x3', '\x2', '\x2', '\x2', '\x19', 'Y', '\x3', '\x2', '\x2', '\x2', 
		'\x1B', '[', '\x3', '\x2', '\x2', '\x2', '\x1D', ']', '\x3', '\x2', '\x2', 
		'\x2', '\x1F', '_', '\x3', '\x2', '\x2', '\x2', '!', '\x61', '\x3', '\x2', 
		'\x2', '\x2', '#', '\x63', '\x3', '\x2', '\x2', '\x2', '%', '\x65', '\x3', 
		'\x2', '\x2', '\x2', '\'', 'g', '\x3', '\x2', '\x2', '\x2', ')', 'j', 
		'\x3', '\x2', '\x2', '\x2', '+', 'm', '\x3', '\x2', '\x2', '\x2', '-', 
		'\x81', '\x3', '\x2', '\x2', '\x2', '/', '\x8D', '\x3', '\x2', '\x2', 
		'\x2', '\x31', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x33', '\xA0', '\x3', 
		'\x2', '\x2', '\x2', '\x35', '\xA7', '\x3', '\x2', '\x2', '\x2', '\x37', 
		'\x38', '\a', '<', '\x2', '\x2', '\x38', '\x4', '\x3', '\x2', '\x2', '\x2', 
		'\x39', ':', '\a', 'v', '\x2', '\x2', ':', ';', '\a', 't', '\x2', '\x2', 
		';', '<', '\a', 'w', '\x2', '\x2', '<', '=', '\a', 'g', '\x2', '\x2', 
		'=', '\x6', '\x3', '\x2', '\x2', '\x2', '>', '?', '\a', 'h', '\x2', '\x2', 
		'?', '@', '\a', '\x63', '\x2', '\x2', '@', '\x41', '\a', 'n', '\x2', '\x2', 
		'\x41', '\x42', '\a', 'u', '\x2', '\x2', '\x42', '\x43', '\a', 'g', '\x2', 
		'\x2', '\x43', '\b', '\x3', '\x2', '\x2', '\x2', '\x44', '\x45', '\a', 
		't', '\x2', '\x2', '\x45', '\x46', '\a', 'i', '\x2', '\x2', '\x46', 'G', 
		'\a', '\x64', '\x2', '\x2', 'G', '\n', '\x3', '\x2', '\x2', '\x2', 'H', 
		'I', '\a', 'k', '\x2', '\x2', 'I', 'J', '\a', 'p', '\x2', '\x2', 'J', 
		'K', '\a', 'v', '\x2', '\x2', 'K', 'L', '\a', '\x34', '\x2', '\x2', 'L', 
		'\f', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\a', '&', '\x2', '\x2', 'N', 
		'\xE', '\x3', '\x2', '\x2', '\x2', 'O', 'P', '\a', '}', '\x2', '\x2', 
		'P', '\x10', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\a', '\x7F', '\x2', 
		'\x2', 'R', '\x12', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\a', '*', '\x2', 
		'\x2', 'T', '\x14', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\a', '+', '\x2', 
		'\x2', 'V', '\x16', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\a', ']', '\x2', 
		'\x2', 'X', '\x18', '\x3', '\x2', '\x2', '\x2', 'Y', 'Z', '\a', '_', '\x2', 
		'\x2', 'Z', '\x1A', '\x3', '\x2', '\x2', '\x2', '[', '\\', '\a', '/', 
		'\x2', '\x2', '\\', '\x1C', '\x3', '\x2', '\x2', '\x2', ']', '^', '\a', 
		'#', '\x2', '\x2', '^', '\x1E', '\x3', '\x2', '\x2', '\x2', '_', '`', 
		'\a', ',', '\x2', '\x2', '`', ' ', '\x3', '\x2', '\x2', '\x2', '\x61', 
		'\x62', '\a', '\x31', '\x2', '\x2', '\x62', '\"', '\x3', '\x2', '\x2', 
		'\x2', '\x63', '\x64', '\a', '\'', '\x2', '\x2', '\x64', '$', '\x3', '\x2', 
		'\x2', '\x2', '\x65', '\x66', '\a', '-', '\x2', '\x2', '\x66', '&', '\x3', 
		'\x2', '\x2', '\x2', 'g', 'h', '\a', '(', '\x2', '\x2', 'h', 'i', '\a', 
		'(', '\x2', '\x2', 'i', '(', '\x3', '\x2', '\x2', '\x2', 'j', 'k', '\a', 
		'~', '\x2', '\x2', 'k', 'l', '\a', '~', '\x2', '\x2', 'l', '*', '\x3', 
		'\x2', '\x2', '\x2', 'm', 'q', '\t', '\x2', '\x2', '\x2', 'n', 'p', '\t', 
		'\x3', '\x2', '\x2', 'o', 'n', '\x3', '\x2', '\x2', '\x2', 'p', 's', '\x3', 
		'\x2', '\x2', '\x2', 'q', 'o', '\x3', '\x2', '\x2', '\x2', 'q', 'r', '\x3', 
		'\x2', '\x2', '\x2', 'r', '~', '\x3', '\x2', '\x2', '\x2', 's', 'q', '\x3', 
		'\x2', '\x2', '\x2', 't', 'u', '\a', '\x30', '\x2', '\x2', 'u', 'y', '\t', 
		'\x2', '\x2', '\x2', 'v', 'x', '\t', '\x3', '\x2', '\x2', 'w', 'v', '\x3', 
		'\x2', '\x2', '\x2', 'x', '{', '\x3', '\x2', '\x2', '\x2', 'y', 'w', '\x3', 
		'\x2', '\x2', '\x2', 'y', 'z', '\x3', '\x2', '\x2', '\x2', 'z', '}', '\x3', 
		'\x2', '\x2', '\x2', '{', 'y', '\x3', '\x2', '\x2', '\x2', '|', 't', '\x3', 
		'\x2', '\x2', '\x2', '}', '\x80', '\x3', '\x2', '\x2', '\x2', '~', '|', 
		'\x3', '\x2', '\x2', '\x2', '~', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x7F', 
		',', '\x3', '\x2', '\x2', '\x2', '\x80', '~', '\x3', '\x2', '\x2', '\x2', 
		'\x81', '\x87', '\a', '$', '\x2', '\x2', '\x82', '\x83', '\a', '^', '\x2', 
		'\x2', '\x83', '\x86', '\t', '\x4', '\x2', '\x2', '\x84', '\x86', '\n', 
		'\x5', '\x2', '\x2', '\x85', '\x82', '\x3', '\x2', '\x2', '\x2', '\x85', 
		'\x84', '\x3', '\x2', '\x2', '\x2', '\x86', '\x89', '\x3', '\x2', '\x2', 
		'\x2', '\x87', '\x85', '\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\x3', 
		'\x2', '\x2', '\x2', '\x88', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x89', 
		'\x87', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\a', '$', '\x2', 
		'\x2', '\x8B', '.', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8E', '\a', 
		'/', '\x2', '\x2', '\x8D', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x8E', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x98', '\x3', '\x2', '\x2', 
		'\x2', '\x8F', '\x90', '\x5', '\x35', '\x1B', '\x2', '\x90', '\x91', '\a', 
		'\x30', '\x2', '\x2', '\x91', '\x92', '\x5', '\x35', '\x1B', '\x2', '\x92', 
		'\x99', '\x3', '\x2', '\x2', '\x2', '\x93', '\x94', '\a', '\x30', '\x2', 
		'\x2', '\x94', '\x99', '\x5', '\x35', '\x1B', '\x2', '\x95', '\x96', '\x5', 
		'\x35', '\x1B', '\x2', '\x96', '\x97', '\a', '\x30', '\x2', '\x2', '\x97', 
		'\x99', '\x3', '\x2', '\x2', '\x2', '\x98', '\x8F', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '\x93', '\x3', '\x2', '\x2', '\x2', '\x98', '\x95', '\x3', 
		'\x2', '\x2', '\x2', '\x99', '\x30', '\x3', '\x2', '\x2', '\x2', '\x9A', 
		'\x9C', '\a', '/', '\x2', '\x2', '\x9B', '\x9A', '\x3', '\x2', '\x2', 
		'\x2', '\x9B', '\x9C', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x9D', '\x3', 
		'\x2', '\x2', '\x2', '\x9D', '\x9E', '\x5', '\x35', '\x1B', '\x2', '\x9E', 
		'\x32', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA1', '\t', '\x6', '\x2', 
		'\x2', '\xA0', '\x9F', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA2', '\x3', 
		'\x2', '\x2', '\x2', '\xA2', '\xA0', '\x3', '\x2', '\x2', '\x2', '\xA2', 
		'\xA3', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', '\x3', '\x2', '\x2', 
		'\x2', '\xA4', '\xA5', '\b', '\x1A', '\x2', '\x2', '\xA5', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\xA6', '\xA8', '\t', '\a', '\x2', '\x2', '\xA7', 
		'\xA6', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\x3', '\x2', '\x2', 
		'\x2', '\xA9', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xAA', '\x3', 
		'\x2', '\x2', '\x2', '\xAA', '\x36', '\x3', '\x2', '\x2', '\x2', '\r', 
		'\x2', 'q', 'y', '~', '\x85', '\x87', '\x8D', '\x98', '\x9B', '\xA2', 
		'\xA9', '\x3', '\x2', '\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Butjok.Parsers
